[tool.poetry]
name = "edspdf"
version = "0.3.2"
description = "Smart text extraction from PDF documents"
authors = ["Basile Dura <basile.dura-ext@aphp.fr>"]
license = "BSD-3"
readme = "README.md"
homepage = "https://datasciencetools-pages.eds.aphp.fr/edspdf/"
repository = "https://gitlab.eds.aphp.fr/datasciencetools/edspdf"
documentation = "https://datasciencetools-pages.eds.aphp.fr/edspdf/"

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.6.0"
pandas = "^1.4.2"
scikit-learn = "^1.0.2"
"pdfminer.six" = "^20220319"
pydantic = "^1.2"
catalogue = "^2.0.7"
thinc = "^8.0.15"
networkx = "^2.8"
scipy = "^1.5.0"
pdf2image = "^1.16.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
jupyter = "^1.0.0"
jupytext = "^1.13.8"
pre-commit = "^2.18.1"
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-html = "^3.1.1"
griffe = "^0.19.0"
Jinja2 = ">=2.10.2<=3.0.3"
mike = "^1.1.2"
mkdocs-autorefs = "0.3.1"
mkdocs-bibtex = "^2.0.3"
mkdocs-charts-plugin = "^0.0.8"
mkdocs-gen-files = "^0.3.4"
mkdocs-img2fig-plugin = "^0.9.3"
mkdocs-literate-nav = "^0.4.1"
mkdocs-material = "^8.2.8"
mkdocs-section-index = "^0.3.4"
mkdocstrings = "^0.18.1"
mkdocstrings-python = "^0.6.6"
streamlit = "^1.8.1"
mypy = "^0.950"

[tool.interrogate]
ignore-init-method = true
ignore-init-module = true
ignore-magic = false
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = true
ignore-nested-functions = false
ignore-nested-classes = true
ignore-setters = false
fail-under = 10
exclude = ["docs", "build", "tests"]
verbose = 0
quiet = false
whitelist-regex = []
color = true
omit-covered-files = false

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.mypy]
plugins = "pydantic.mypy"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
