[project]
name = "edspdf"
description = "Smart text extraction from PDF documents"
authors = [
    {name = "Perceval Wajsburt", email = "perceval.wajsburt-ext@aphp.fr"},
    {name = "Alice Calliger", email = "alice.calliger-ext@aphp.fr"},
    {name = "Basile Dura", email = "basile.dura-ext@aphp.fr"},
]
license = {file="LICENSE"}
readme="README.md"
urls.homepage="https://github.com/aphp/edspdf/"
urls.repository="https://github.com/aphp/edspdf/"
urls.documentation="https://aphp.github.io/edspdf/"
dynamic = ["version"]
requires-python=">3.7.6,<4.0,!=3.8.1"

dependencies=[
    "loguru>=0.6.0,<1.0.0",
    "pandas>=1.2,<2.0.0",
    "scikit-learn>=1.0.2,<2.0.0",
    "pydantic>=1.2,<2.0.0",
    "catalogue~=2.0",
    "networkx~=2.6",
    "typer>=0.6.1,<1.0.0",
    "torch<1.13.0",

    "accelerate>=0.12.0,<1.0.0",
    "Unidecode~=1.3",
    "tqdm~=4.64.1",
    "srsly~=2.4.4",
    "regex",

    "pdfminer.six>=20220319",
    "pypdfium2~=2.7",
    "rich-logger>=0.3.0,<1.0.0",
]

[project.optional-dependencies]
dev=[
    "black==22.6.0",
    "flake8>=3.0",
    "pre-commit>=2.18",
    "pytest==7.1.1",
    "pytest-cov==3.0.0",
    "mypy>=1.0.0",
    "streamlit>=1.19",
    "coverage>=6.5.0",
    "datasets~=2.10",
    "huggingface_hub>=0.8.1",
]
docs=[
    "mike~=1.1.2",
    "mkdocs-bibtex~=2.8.14",
    "mkdocs-gen-files~=0.4.0",
    "mkdocs-literate-nav~=0.6.0",
    "mkdocs-material~=9.1.0",
    "mkdocstrings~=0.20.0",
    "mkdocstrings-python~=0.8.3",
    "mkdocs-glightbox~=0.3.1",
    "mkdocs-autorefs~=0.4.1",
]

[tool.setuptools.dynamic]
version = { attr = "edspdf.__version__" }

[tool.setuptools.packages.find]
where = ["."]

[tool.interrogate]
ignore-init-method=true
ignore-init-module=true
ignore-magic=false
ignore-semiprivate=false
ignore-private=false
ignore-property-decorators=false
ignore-module=true
ignore-nested-functions=false
ignore-nested-classes=true
ignore-setters=false
fail-under=10
exclude=["docs", "build", "tests"]
verbose=0
quiet=false
whitelist-regex=[]
color=true
omit-covered-files=false

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.mypy]
plugins = "pydantic.mypy"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
